### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by JenningsL** [fangchangma/self-supervised-depth-completion#13]
When I try to run with test_completion split. I got the following error: 

```
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main()
  File "main.py", line 231, in main
    result, is_best = iterate("test_completion", args, val_loader, model, None, logger, checkpoint['epoch'])
  File "main.py", line 105, in iterate
    pred = model(batch_data)
  File "/data/ssd/public/jlliu/pythonlib/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/ssd/public/jlliu/pythonlib/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/data/ssd/public/jlliu/pythonlib/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/ssd/public/jlliu/self-supervised-depth-completion/model.py", line 126, in forward
    y = torch.cat((convt5, conv5), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 47 and 48 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:83
```

**Comment by wuheng199112068** [comment]
An error occurred when entering such a parameter on the command line，what can we input about [checkpoint -path]？Can you give us an example?

Namespace(batch_size=1, criterion='l2', epochs=11, evaluate='[checkpoint-path]', i
nput='gd', jitter=0.1, layers=34, lr=1e-05, pretrained=False, print_freq=10, rank_metric='rmse', result='..\results', resume='', start_epoch=0, train_mode='dense', use_d=True, use_g=True, use_pose=False, use_rgb=False, val='select', w1=0, w2=0, weight_decay=0, workers=4)
=> no model found at '[checkpoint-path]'
