### ISSUE TITLE
python main.py --evaluate [checkpoint-path]

### ISSUE THREAD

**Issue by wuheng199112068** [fangchangma/self-supervised-depth-completion#15]
An error occurred when entering such a parameter on the command line，what can we input about [checkpoint -path]？Can you give us an example?

Namespace(batch_size=1, criterion='l2', epochs=11, evaluate='[checkpoint-path]', i
nput='gd', jitter=0.1, layers=34, lr=1e-05, pretrained=False, print_freq=10, rank_metric='rmse', result='..\\results', resume='', start_epoch=0, train_mode='dense', use_d=True, use_g=True, use_pose=False, use_rgb=False, val='select', w1=0, w2=0, weight_decay=0, workers=4)
=> no model found at '[checkpoint-path]'

**Comment by jadhu22** [comment]
python main.py --evaluate /home/jadoo/dense_lidar/checkpoint/model_best.pth.tar

**Comment by fangchangma** [comment]
> Can you give us an example?

Akash gave an excellent example. 

Also, please do not post the same question repeatedly.

**Comment by wuheng199112068** [comment]
thanks for your reply. It worked the way you gave it, but it still went wrong. What can we do?
=> checkpoint loaded.
=> creating model and optimizer...
=> model and optimizer created.
Traceback (most recent call last):
  File "main.py", line 247, in <module>
    main()
  File "main.py", line 204, in main
    model.load_state_dict(checkpoint['model'])
  File "D:\Users\USER_CC\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DepthCompletionNet:
        Unexpected key(s) in state_dict: "conv1_d.1.num_batches_tracked", "conv1_img.1.num_batches_tracked", "conv2.0.bn1.num_batches_tracked", "conv2.0.bn2.num_batches_tracked", "conv2.1.bn1.num_batches_tracked", "conv2.1.bn2.num_batches_tracked", "conv2.2.bn1.num_batches_tracked", "conv2.2.bn2.num_batches_tracked", "conv3.0.bn1.num_batches_tracked", "conv3.0.bn2.num_batches_tracked", "conv3.0.downsample.1.num_batches_tracked", "conv3.1.bn1.num_batches_tracked", "conv3.1.bn2.num_batches_tracked", "conv3.2.bn1.num_batches_tracked", "conv3.2.bn2.num_batches_tracked", "conv3.3.bn1.num_batches_tracked", "conv3.3.bn2.num_batches_tracked", "conv4.0.bn1.num_batches_tracked", "conv4.0.bn2.num_batches_tracked", "conv4.0.downsample.1.num_batches_tracked", "conv4.1.bn1.num_batches_tracked", "conv4.1.bn2.num_batches_tracked", "conv4.2.bn1.num_batches_tracked", "conv4.2.bn2.num_batches_tracked", "conv4.3.bn1.num_batches_tracked", "conv4.3.bn2.num_batches_tracked", "conv4.4.bn1.num_batches_tracked", "conv4.4.bn2.num_batches_tracked", "conv4.5.bn1.num_batches_tracked", "conv4.5.bn2.num_batches_tracked", "conv5.0.bn1.num_batches_tracked", "conv5.0.bn2.num_batches_tracked", "conv5.0.downsample.1.num_batches_tracked", "conv5.1.bn1.num_batches_tracked", "conv5.1.bn2.num_batches_tracked", "conv5.2.bn1.num_batches_tracked", "conv5.2.bn2.num_batches_tracked", "conv6.1.num_batches_tracked", "convt5.1.num_batches_tracked", "convt4.1.num_batches_tracked", "convt3.1.num_batches_tracked", "convt2.1.num_batches_tracked", "convt1.1.num_batches_tracked".
