### ISSUE TITLE
Running Error in train mode sparse+photo

### ISSUE THREAD

**Issue by hongshenggeng** [fangchangma/self-supervised-depth-completion#52]
Hi， Fangchang Ma:
      After downloading the dataSet required and put them at the tree structure showed in readme, I try to run the demo using command "python main.py --train-mode sparse+photo -b 6". It meets error as follow:

'''
=> output: ../results/mode=sparse+photo.w1=0.1.w2=0.1.input=gd.resnet34.criterion=l2.lr=1e-05.bs=6.wd=0.pretrained=False.jitter=0.1.time=2021-05-10@12-35
Train Epoch: 0 [9290/14317]     lr=1e-05 t_Data=0.009(0.008) t_GPU=0.395(0.402)
        RMSE=3337.93(10104.38) MAE=1233.75(5881.38) iRMSE=11.95(inf) iMAE=5.93(inf)
        silog=11.96(nan) squared_rel=0.02(0.24) Delta1=0.954(0.600) REL=0.066(0.333)
        Lg10=0.029(nan) Photometric=39.012(56.714)

Traceback (most recent call last):
  File "main.py", line 362, in <module>
    main()
  File "main.py", line 349, in main
    epoch)  # train for one epoch
  File "main.py", line 171, in iterate
    for i, batch_data in enumerate(loader):
  File "/home/hsg/data/software/anaconda/envs/hsg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/hsg/data/software/anaconda/envs/hsg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/home/hsg/data/software/anaconda/envs/hsg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/hsg/data/software/anaconda/envs/hsg/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/hsg/data/software/anaconda/envs/hsg/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hsg/data/software/anaconda/envs/hsg/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hsg/data/software/anaconda/envs/hsg/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hsg/data/proj/SSDC/self-supervised-depth-completion/dataloaders/kitti_loader.py", line 306, in __getitem__
    rgb, sparse, target, rgb_near = self.__getraw__(index)
  File "/home/hsg/data/proj/SSDC/self-supervised-depth-completion/dataloaders/kitti_loader.py", line 300, in __getraw__
    self.paths['gt'][index] is not None else None
  File "/home/hsg/data/proj/SSDC/self-supervised-depth-completion/dataloaders/kitti_loader.py", line 156, in depth_read
    depth_png = np.array(img_file, dtype=int)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'PngImageFile'
'''

Could anyone help me to solve the problem?
Or provide some suggestion?

Thanks!

**Comment by onionysy** [comment]
sorry to bother you, I have meet the same question. Can you tell me how to solve the problem?
